DELETE http://localhost:3001/api/users/1
Content-Type: application/json

### delete blog
DELETE http://localhost:3001/api/blogs/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBldHJpQHBldHJpLmZpIiwiaWQiOjQsImlhdCI6MTY3NjgwODI1OH0.b8102jsJ2gdoqpFasu3vVU0baWsRG-_wsdWiM-fM4qo
