DELETE http://localhost:3001/api/users/1
Content-Type: application/json

### delete blog
DELETE http://localhost:3001/api/blogs/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBldHJpQHBldHJpLmZpIiwiaWQiOjEsImlhdCI6MTY3ODE4NzQ1N30.ZANj1TIlWX6kBQ8hDKM8u0xM38u6UoNl50kfw2l7j8U

###
DELETE http://localhost:3001/api/logout/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBldHJpQHBldHJpLmZpIiwiaWQiOjEsImlhdCI6MTY3ODE4NjkyNH0.o4i2k7OBYssnUidQF1RjsIBwyA5ggTXu6jyK34ua5Xc
