PUT http://localhost:3001/api/blogs/8
Content-Type: application/json

{
  "likes": 1
}

###
PUT http://localhost:3001/api/users/petrii@petri.fi
Content-Type: application/json

{
  "username": "petri@petri.fi"
}